Species=[
    ('D', 'Canine'),
    ('C', 'Feline'),
    ('H', 'Horse'),
    ('E', 'Exotic'),
    ('F', 'Fish'),
    ('B', 'Bird'),
    ('R', 'Rodent'),
]

Sex = [
    ('M', 'Male'),
    ('F', 'Female'),
]

YorN = [
    ('Y', 'Yes'),
    ('N', 'No'),
]

Dispostions = [
    (1, 'Happy'),
    (2, 'Friendly'),
    (3, 'Aggressive'),
    (4, 'Skittish'),
    (5, 'Sensitive'),
    (6, 'Sociable'),
    (7, 'Scared'),
    
]
Canine = [

    ('Affenpinscher','Affenpinscher'),
    ('Afghan Hound','Afghan Hound'),
    ('Airedale Terrier','Airedale Terrier'),
    ('Akita','Akita'),
    ('Alaskan Malamute','Alaskan Malamute'),
    ('American Staffordshire Terrier','American Staffordshire Terrier'),
    ('American Water Spaniel','American Water Spaniel'),
    ('Australian Cattle Dog','Australian Cattle Dog'),
    ('Australian Shepherd','Australian Shepherd'),
    ('Australian Terrier','Australian Terrier'),
    ('Basenji','Basenji'),
    ('Basset Hound','Basset Hound'),
    ('Beagle','Beagle'),
    ('Bearded Collie','Bearded Collie'),
    ('Bedlington Terrier','Bedlington Terrier'),
    ('Bernese Mountain Dog','Bernese Mountain Dog'),
    ('Bichon Frise','Bichon Frise'),
    ('Black And Tan Coonhound','Black And Tan Coonhound'),
    ('Bloodhound','Bloodhound'),
    ('Border Collie','Border Collie'),
    ('Border Terrier','Border Terrier'),
    ('Borzoi','Borzoi'),
    ('Boston Terrier','Boston Terrier'),
    ('Bouvier Des Flandres','Bouvier Des Flandres'),
    ('Boxer','Boxer'),
    ('Briard','Briard'),
    ('Brittany','Brittany'),
    ('Brussels Griffon','Brussels Griffon'),
    ('Bull Terrier','Bull Terrier'),
    ('Bulldog','Bulldog'),
    ('Bullmastiff','Bullmastiff'),
    ('Cairn Terrier','Cairn Terrier'),
    ('Canaan Dog','Canaan Dog'),
    ('Chesapeake Bay Retriever','Chesapeake Bay Retriever'),
    ('Chihuahua','Chihuahua'),
    ('Chinese Crested','Chinese Crested'),
    ('Chinese Shar-Pei','Chinese Shar-Pei'),
    ('Chow Chow','Chow Chow'),
    ('Clumber Spaniel','Clumber Spaniel'),
    ('Cocker Spaniel','Cocker Spaniel'),
    ('Collie','Collie'),
    ('Curly-Coated Retriever','Curly-Coated Retriever'),
    ('Dachshund','Dachshund'),
    ('Dalmatian','Dalmatian'),
    ('Doberman Pinscher','Doberman Pinscher'),
    ('English Cocker Spaniel','English Cocker Spaniel'),
    ('English Setter','English Setter'),
    ('English Springer Spaniel','English Springer Spaniel'),
    ('English Toy Spaniel','English Toy Spaniel'),
    ('Eskimo Dog','Eskimo Dog'),
    ('Finnish Spitz','Finnish Spitz'),
    ('Flat-Coated Retriever','Flat-Coated Retriever'),
    ('Fox Terrier','Fox Terrier'),
    ('Foxhound','Foxhound'),
    ('French Bulldog','French Bulldog'),
    ('German Shepherd','German Shepherd'),
    ('German Shorthaired Pointer','German Shorthaired Pointer'),
    ('German Wirehaired Pointer','German Wirehaired Pointer'),
    ('Golden Retriever','Golden Retriever'),
    ('Gordon Setter','Gordon Setter'),
    ('Great Dane','Great Dane'),
    ('Greyhound','Greyhound'),
    ('Irish Setter','Irish Setter'),
    ('Irish Water Spaniel','Irish Water Spaniel'),
    ('Irish Wolfhound','Irish Wolfhound'),
    ('Jack Russell Terrier','Jack Russell Terrier'),
    ('Japanese Spaniel','Japanese Spaniel'),
    ('Keeshond','Keeshond'),
    ('Kerry Blue Terrier','Kerry Blue Terrier'),
    ('Komondor','Komondor'),
    ('Kuvasz','Kuvasz'),
    ('Labrador Retriever','Labrador Retriever'),
    ('Lakeland Terrier','Lakeland Terrier'),
    ('Lhasa Apso','Lhasa Apso'),
    ('Maltese','Maltese'),
    ('Manchester Terrier','Manchester Terrier'),
    ('Mastiff','Mastiff'),
    ('Mexican Hairless','Mexican Hairless'),
    ('Newfoundland','Newfoundland'),
    ('Norwegian Elkhound','Norwegian Elkhound'),
    ('Norwich Terrier','Norwich Terrier'),
    ('Otterhound','Otterhound'),
    ('Papillon','Papillon'),
    ('Pekingese','Pekingese'),
    ('Pointer','Pointer'),
    ('Pomeranian','Pomeranian'),
    ('Poodle','Poodle'),
    ('Pug','Pug'),
    ('Puli','Puli'),
    ('Rhodesian Ridgeback','Rhodesian Ridgeback'),
    ('Rottweiler','Rottweiler'),
    ('Saint Bernard','Saint Bernard'),
    ('Saluki','Saluki'),
    ('Samoyed','Samoyed'),
    ('Schipperke','Schipperke'),
    ('Schnauzer','Schnauzer'),
    ('Scottish Deerhound','Scottish Deerhound'),
    ('Scottish Terrier','Scottish Terrier'),
    ('Sealyham Terrier','Sealyham Terrier'),
    ('Shetland Sheepdog','Shetland Sheepdog'),
    ('Shih Tzu','Shih Tzu'),
    ('Siberian Husky','Siberian Husky'),
    ('Silky Terrier','Silky Terrier'),
    ('Skye Terrier','Skye Terrier'),
    ('Staffordshire Bull Terrier','Staffordshire Bull Terrier'),
    ('Soft-Coated Wheaten Terrier','Soft-Coated Wheaten Terrier'),
    ('Sussex Spaniel','Sussex Spaniel'),
    ('Spitz','Spitz'),
    ('Tibetan Terrier','Tibetan Terrier'),
    ('Vizsla','Vizsla'),
    ('Weimaraner','Weimaraner'),
    ('Welsh Terrier','Welsh Terrier'),
    ('West Highland White Terrier','West Highland White Terrier'),
    ('Whippet','Whippet'),
    ('Yorkshire Terrier', 'Yorkshire Terrier'),

]